# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# bright cove
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '15.5'
prepare_react_native_project!

use_frameworks! :linkage => :static



linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

use_modular_headers!

project 'lexMobileApp', {
  'DebugStage' => :debug,
  'DebugProd' => :debug,
  'ReleaseStage' => :release,
  'ReleaseProd' => :release
}


target 'lexMobileApp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  debugs = ['DebugStage', 'DebugProd']

  # To pick environment config
  pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/@code-push-next/react-native-code-push'
  # Flags change depending on the env values.
  flags = get_default_flags()

  pod 'Brightcove-Player-Core/XCFramework'

  use_react_native!(
    :path => config[:reactNativePath],

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  # RCTLinking use for deep linking
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.aggregate_targets.each do |aggregate_target|
      project = aggregate_target.user_project
      project.build_configurations.each do |config|
        if config.name.downcase.include?("debug")
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= '$(inherited) DEBUG'
        end
      end
      project.save
    end

    bitcode_strip_path = `xcrun --find bitcode_strip`.chomp
    unless bitcode_strip_path.empty?
      def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
        framework_path = File.join(Dir.pwd, framework_relative_path)
        if File.exist?(framework_path)
          command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
          puts "Stripping bitcode: #{command}"
          system(command)
        else
          puts "Framework not found at path: #{framework_path}, skipping bitcode strip."
        end
      end

      framework_paths = [
        "Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
        "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
        "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
        "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
        "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes"
      ]

      framework_paths.each do |framework_relative_path|
        strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      end
    else
      puts "bitcode_strip tool not found, skipping bitcode stripping."
    end
  end
end
