export const data = {
	longString: "a".repeat(60),
	shortString: "short string",
	content: "content",
	title: "Title",
	value: "Value",
	assetName: "Asset Name",
	learningPathName: "Learning Path Name",
	fileUrl: "http://example.com/path/to/file.txt",
	base64String: "a".repeat(4000),
	showToast: jest.fn(),
	base64string: "base64string",
	issueDescription: "Sample issue description",
	sampleAsset: "Sample Asset",
	sampleLearningPath: "Sample Learning Path",
	sampleQuestion: "Sample Question",
	sampleCourse: "Sample Course",
	sampleModule: "Sample Module",
	sampleSession: "Sample Session",
	sampleSegment: "Sample Segment",
	issueType: "Content Error",
};
