export const strings = {
	HOME: "Home",
	BACK: "Back",
	PREV: "Prev",
	SKIP: "Skip",
	NEXT: "Next",
	OOPS: "Oops!",
	FINISH: "Finish",
	WEEKS: "Modules",
	OKAY: "Okay",
	CLOSE: "Close",
	NEW_CONVERSATION_START_BOT:
		"Are you sure you want to start a new conversation? ",
	PREVIOUS_CHAT_HISTORY_LOST_TEXT:
		"All your previous chat history will be lost",
	MAX_LIMIT_TEXT: "Max 200 characters required",
	REASON_TEXT: "Write your reason here.",
	YOU_ARE_IN_COACH_MODE_NOW: "You are in Coach Mode now",
	USER_FEEDBACK_MODAL_HEADING: "Let us know how we did",
	YOU_HAVENT_ENROLLED_IN_ANY_COURSES_YET:
		"You haven't enrolled in any courses yet, but your learning journey is just one step away!",
	APPRECIATE_FEEDBACK_TEXT:
		"We’d appreciate your feedback on the previous conversation",
	SIGN_IN_TO_ACCESS_PROGRAMS: "Sign In to access your enrolled Programs.",
	SIGN_IN_TO_ACCESS_ACADEMIC_PLANNER:
		"Sign In to access your Academic Planner.",
	EXIT_COACH_MODE: "Exit Coach Mode",
	EXIT_COACH_MODE_MODAL_TITLE: "Are you sure you want to exit `Coach Mode`?",
	SURVEY_COMPLETE: "Survey Completed",
	SURVEY_DESCRIPTION:
		"Thank you for completing the Survey. We value your feedback.",
	INSTRUCTION: "Instructions :",
	DESCRIPTIONS: "Description :",
	SKILLS: "Skills :",
	UH_OH: "Uh Oh!",
	ENTERRESPONSE: "Enter your response here",
	YES: "Yes",
	NO: "No",
	PREVIEW: "Preview",
	QUESTION_OVERVIEW: "Question Overview",
	MARKED: "Marked",
	ANSWERED: "Answered",
	DONTSHOWAGAIN: "Don't show this message again",
	CANNOTCOMEBACK: "You will not be able to come back to this question",
	ATTEMPT: "Attempt this quesion in",
	NOT_ANSWERED: "Not Answered",
	SINGLE_SELECTION: "Single Selection",
	CHANGE_PROFILE_PICTURE: "Change Profile Picture",
	MULTI_SELECTION: "Multi Selection",
	NUMERICAL_INPUT: "Numerical",
	SKIP_ANYWAY: "Skip Anyway",
	PENALTY_NOTE: "Note",
	LIVE_LEARNING: "Live Learning",
	CAREER_PREP: "Career Prep",
	SEQUENCING: "Sequencing",
	VIEW_MORE: "View More",
	DOUBT_CLOSE: "Doubt form is closed",
	CERTIFICATIONS: "Certifications",
	UPLOAD: "Upload",
	EXPECTED_UPLOAD: "• You are expected to upload",
	UPLOAD_PROFILE_PIC: "Please upload Profile Pic",
	CONTACT_DETAILS: "Contact Details",
	UPLOAD_PROFILE_PICTURE: "Upload Profile Picture",
	REMOVE_PROFILE_PICTURE: "Remove Profile Picture",
	ASPIRATIONS_MY_ACCOUNT: "Aspirations",
	DEDUCTION_PENALTY: "Deduction in Marks due to Penalty",
	TICKET_DESC:
		"Issue with Assessment Engine content that it takes too long to load the content.",
	TO_BE_SCHEDULED: "To be Scheduled",
	SCHEDULED: "Scheduled",
	EXPIRED: "Expired",
	NOT_FROM_INDIA: "Not from India?",
	OPTIONAL_BULLET_TAG: " • Optional",
	USERS_FROM_OUTSIDE:
		"Users from outside India can only sign in using email verification.",
	PROCTOR_TXT:
		"This is a proctored Assessment.\n It can only be attempted on a Desktop. ",
	SIGNIN_WITH_EMAIL: "Sign in with Email",
	SUBMITTING_AFTER: "Submitting after",
	SIGN_IN_EMAIL: "Sign in using",
	SELECT_COURSE: "Select Course",
	SUBMISSIONS: "Submissions: ",
	SUBMITTED_ON: "Submitted on: ",
	SUBMITTED_BY: "Submitted By: ",
	NOTHING_ADDED_YET: "Nothing added yet",
	CANCEL_PENALTY: "On cancelling, you may incur a penalty.",
	EXPECTED_EVALUATION_DATE: "Expected Evaluation Date: ",
	REQUEST_RE_EVALUATION: "Request Re-evaluation: ",
	TO_AVOID_PENALTY: "to avoid penalty.",
	// SUBMISSION_CONSIDERED_ONLY_FOR_EVALUTAION:"Submission will be considered only for evaluation. It will not contribute to your grades.",
	EVALUATION_COMPLETED: "Evaluation Completed: ",
	SUBMISSION_CONSIDERED_ONLY_FOR_EVALUTAION:
		"Submission will be considered only for evaluation. It will not contribute to your grades.",
	RE_EVALUATION_COMPLETED: "Re-evaluation Completed: ",
	RE_EVALUATION_REQUEST_SENT_ON: "Re-evaluation Request sent on: ",
	LOG_IN: "Login",
	UPLOADED: "Uploaded",
	TA_CALL: "TA Call",
	CONDUCTED_OUTSIDE_PRISM: "Conducted Outside Prism",
	SUBMIT_BEFORE: "Submit before",
	LOGIN_TEXT_HEADING: "Future proof your career",
	LOGIN_TEXT_SUBHEADING: "with your lifelong learning partner",
	REVISE_COACH_INPUT: "can you help me revise?",
	COACH_MODE_EXIT_INPUT: "Please exit the coach mode",
	UNIVESITY_PARTNER_DESC:
		"Some features in this program are not compatible with mobile devices. Use your desktop to continue learning",
	DEADLINE: "Extend Due Date",
	MAY_INCUR_PENALTY: "may incur a penalty.",
	EXTENSIONS_AVAILABLE: "Extensions available: ",
	NEED_MORE_TIME:
		"Need more time? Extend Due Date for this module to avoid Penalty.",
	EXTENSION_REGAINED_SUBMISSION_DONE:
		"Extension regained, as submission is done before the due date.",
	EXTENSION_REGAINED_SUBMISSION_NOT_DONE:
		"Extension regained, as submission was not done before the  due date.",
	EXTENSION_APPLIED:
		"Extension applied, Submit by extended due date to avoid penalty.",
	ENTER_VALID_OTP: "Enter a valid OTP",
	OTP_4_DIGITS: "OTP should be 4 digit number",
	OTP_SENT_TEXT: "We have sent a verification code to",
	DIDNT_RECEIVE_OTP: `Didn't receive OTP?  Resend OTP in:`,
	DIDNT_RECEIVE_OTP_SECOND_CASE: "Didn't receive OTP? ",
	DOUBT_SOLVING: "Doubt Solving",
	CAREER_COACHING: "Career Coaching",
	CANCEL_CURRENT_EXTENSION:
		"Cancel your current extension to regain it. Penalties may be incurred.",
	SUBMISSION_BTW_DUE_HARD_DEADLINE:
		"Due date can still be extended to avoid penalty.",
	CANCEL_EXTENSION_BEFORE_HARD_DEADLINE:
		"Cancel extension and submit before due date to regain extension.",
	INVALID_TELEGRAM_OR_EMAIL: "Please add valid Telegram ID or email address",
	ARTIFACTS_TITLE:
		"Some of the artifacts were intended to be available until",
	AADHAR_NO_DIGITS: "Aadhar number should be exactly 12 digits",
	INVALID_AADHAR_NO: "Invalid Aadhar number format",
	ARTIFACTS_SUB_TITLE: "For assistance,contact support@knowledgehut.com.",
	IMPORTANT_LEARNING: "Important Details & Learning Preference",
	RESUME: "Resume",
	UPLOAD_RESUME_TEXT: "Upload your latest Resume",
	PENALTY_OF: "Penalty of",
	COMPONENT: "Component",
	VERIFIED: "Verifiedâœ…",
	TOOTTIP_DATA: "Obtained score / Max score",
	ASPIRATIONS_AND_PREFERENCES: "Aspirations & Preferences",
	PENALTY_TOOLTIP_DESC: "applied on total score due to late submission.",
	PROFESSIONAL: "Professional Deep Dive",
	ENROLL: "Enroll",
	SCORE: "Score",
	AND: " and ",
	OVERALL_SCORE: "Overall Score",
	PHONE_NUMBER: "Phone Number",
	EMAIL: "Email Address",
	EMAIL_TXT: "Email",
	TERMS_AND_CONDITION: " Terms & Conditions",
	TERMS_AND_CONDITIONS_TXT: "TERMS_AND_CONDITION",
	PRIVACY_POLICY: " Privacy Policy",
	PRIVACY_POLICY_TXT: "PRIVACY_POLICY",
	BY_SIGNING_UP: "By Signing In, you agree to upGrad's",
	AADHAR_NO: "Aadhar Number",
	CONTINUE: "Continue",
	LOGIN_OR_SIGNUP_TEXT: "Log In / Sign Up",
	OVERALL_PERCENTAGE_TOOLTIP_DESCRIPTION:
		"Your overall percentage will be recalculated based on your scores and the assigned weightage when they are published",
	CANCEL: "Cancel",
	YODA_BETA_TEXT: `mAI-ask is powered by AI. It is not reflective of expert advice, so check for mistakes. Kindly review `,
	THINKING: "thinking...",
	SIMPLIFY_TOPIC: "Simplify the topic for me",
	WELCOME_MESSAGE:
		`Hi {firstName}, welcome to upGrad 👋` +
		"\n\n" +
		`Let’s get your doubts cleared! How can I assist today?`,
	TICKET: "New Ticket",
	SELECT_FROM_OPTIONS: "Please select from the options above",
	UPGRAD_PRIVACY_POLICY: "https://www.upgrad.com/privacy/",
	UPGRAD_PRIVACY_POLICY_TEXT: "upGrad's Privacy Policy.",
	PLEASE_ENTER_THE: "Please enter the",
	ASK_ME: "Ask Me...",
	INVALID_OTP: "Invalid OTP.",
	INCORRECT_OTP: "Incorrect OTP. Please try again.",
	TICKET_TXT: "Ticket #",
	TICKET_CLOSE_DESC: "Ticket has been closed by Support team",
	MODULE: "Sessions",
	CERTIFICATE_COURSES: "Certification Courses",
	MALE: "MALE",
	EXPLANATION: "Explanation",
	OPTION: "OPTION",
	VERIFY: "Verify",
	SETTINGS_UPDATED: "Settings have been updated successfully",
	AREA_OF_INTEREST_UPDATED: "Area of Interest updated successfully",
	PREVIOUS: "Previous",
	ABOUT_COURSE: "About Course",
	NOT_LIKELY: "Not likely at all ðŸ‘Ž ",
	EXTREMELY_LIKELY: "ðŸ’¯ Extremely likely  ",
	ABSENT: "Absent",
	UPLOAD_FILE: "Upload your file",
	UPLOAD_FILE_LIMIT: "You can upload up to",
	ADD_URL: "Add URL",
	MISSED: "Missed",
	FEMALE: "FEMALE",
	ADD_NOW: "Add Now",
	TECHNICAL_COURSES: "Technical Courses",
	ADD: "Add",
	DISAPPOINTED: "Disappointed",
	MANDATORY: " *",
	MANDATORY_TXT: "Mandatory",
	OTHERS: "OTHERS",
	OTHERS_CAMEL: "Others",
	DULL: "Dull",
	SATISFACTORY: "Satisfactory",
	HAPPY: "Happy",
	WOW: "Wow!",
	ME: " (me)",
	COURSE: "Course",
	HR: " hr ago",
	EXP: "Please describe your experience",
	COMMENT: "Comments (Optional)",
	FEEDBACK_TXT_TITLE: "Howâ€˜s Your Session Going?",
	YOUR_OPINION_VALUABLE: "Your opinion is valuable",
	FEEDBACK_CHOOSE_TXT:
		"Weâ€™re very thrilled that you loved it! What did you like best?",
	BRANCH_TXT: "Branch",
	INSTRUCTORS: "Instructor",
	LINKEDIN: "LINKEDIN",
	PROFILE_PAGE_LOADED: "PROFILE_PAGE_LOADED",
	TICKET_DETAILS_LOADED: "TICKET_DETAILS_LOADED",
	MY_ACCOUNTS_PAGE_LOADED: "MY_ACCOUNTS_PAGE_LOADED",
	PERSONAL_DETAILS_PAGE_LOADED: "PERSONAL_DETAILS_PAGE_LOADED",
	SELECT_OPTION: "Select an option",
	MOST_RECENT_EDUC: "Most Recent Education",
	FIRST_NAME: "First Name",
	PRIMARY_EMAIL: "Primary Email",
	FINISH_QUIZ: "Finish",
	MOBILE_NUMBER: "Mobile Number",
	LAST_NAME: "Last Name",
	ALTERNATIVE_EMAIL: "Alternate Email",
	TELEGRAM_ID: "Telegram ID",
	IAM: "I am a ",
	ABOUT_ERR_COND: "Should not be more than 1200 characters",
	ABOUT_TXT_ERR_COND: "Text should not be more than 1200 characters",
	STUDENT: "STUDENT",
	FRESHER: "FRESHER",
	END_YR: "End Year is required",
	WORKING_PROFESSIONAL: "WORKING PROFESSIONAL",
	ABOUT: "About",
	ABOUT_SUBTITLE:
		"You can write about your years of experience, industry, or skills. People also talk about their achievements or previous job experiences.",
	UNDERSTAND_MY_RESULT: "Understand My Results",
	NO_SLOT: "No Slot Available for ",
	ALL_FIELDS: "All Fields are mandatory",
	CHAR_LIMIT: "/ 1200",
	CERTIFICATE: "Certificate",
	CERTIFICATES: "Certificates",
	BRANCH: "Branch/ Specialization",
	EXTERNAL_CERTIFICATE: "External Certificate",
	MIN: " min ago",
	NO_EXTENSION_LEFT:
		"This will be the final extension allowed. No further extensions will be available for you.",
	OPTIONAL_TXT_ASST:
		"This asset is optional and does not affect your progress",
	FIRST_NAME_REQUIRED: "First Name is required",
	LAST_NAME_REQUIRED: "Last Name is required",
	DOB_REQUIRED: "Date of birth is required",
	CITY_REQUIRED: "City is required",
	GENDER_REQUIRED: "Gender is required",
	STATE_REQUIRED: "State is required",
	EXP_L1: "Entry-Level (0-1 years)",
	EXP_L2: "Junior (1-3 years)",
	EXP_L3: "Mid-Level (3-5 years)",
	EXP_L4: "Senior (5-10 years)",
	EXP_L5: "Leadership (10+ Years)",
	ANY: "Any",
	REMOTE: "Remote",
	ONSITE: "Onsite",
	HYBRID: "Hybrid",
	NOTICE_PERIOD_L1: "Immediate",
	NOTICE_PERIOD_L2: "Less than 30 days",
	NOTICE_PERIOD_L3: "30 to 60 days",
	NOTICE_PERIOD_L4: "More than 60 days",
	CTC_L1: "Under 5 LPA   :  Under $6,800",
	CTC_L2: "5 - 8 LPA     :  $6,800 - $10,900",
	CTC_L3: "8 - 12 LPA    :  $10,900 - $16,300",
	CTC_L4: "12 - 15 LPA   :  $16,300 - $20,400",
	CTC_L5: "15 - 20 LPA   :  $20,400 - $27,200",
	CTC_L6: "20 - 25 LPA   :  $27,200 - $34,000",
	CTC_L7: "25 - 30 LPA   :  $34,000 - $40,800",
	CTC_L8: "30 - 40 LPA   :  $40,800 - $54,400",
	CTC_L9: "40 - 50 LPA   :  $54,400 - $68,000",
	CTC_L10: "Above 50 LPA  :  Above $68,000",
	NOT_APPLICABLE: "Not Applicable",
	NEGOTIABLE: "Negotiable",
	NATIONALITY_REQUIRED: "Nationality is required",
	COUNTRY_REQUIRED: "Country is required",
	TIMEZONE_REQUIRED: "TimeZone is  required",
	RESUME_REQUIRED: "Please upload resume",
	LINKEDIN_REQUIRED: "LinkedIn is required",
	ENTER_VALID_URL: "Please enter valid URL",
	EDITED: " â€¢ Edited",
	IS_REQUIRED: "is required",
	PERCENTAGE_ERROR: "Percentage should be a number between 0 and 99",
	PERCENTAGE_REQUIRED: "Percentage is required",
	BRANCH_REQUIRED: "Branch is required",
	START_YR: "Start Year is required",
	UNIVERSITY_REQUIRED: "University is required",
	PROFESSION_REQUIRED: "Profession is required",
	PROFESSION_TXT: "Profession",
	EDUCATION: "Education",
	REOPEN: "Reopen Ticket",
	PREFER_WORK_MODE: "Preferred Work Mode",
	PREFER_JOB_LOC: "Preferred Job Location",
	PREFER_JOB_LOC_DESC: "You can select up to 3 locations",
	RECENT_REQUIRED_TXT: "Recent Education",
	RE_SCHEDULE_SUCCESS: "Session Re-scheduled successfully",
	RE_SCHEDULE_FAIL: "Re-scheduling failed...Please try again later",
	RECENT_EDUCATION: "Recent Education is required",
	DEGREE_REQUIRED: "Degree is required",
	WORK_EXP: "Work Experience",
	AREA_OF_INTEREST: "Area of Interest",
	AGILE_SCRUM: "Agile and Scrum",
	IMPORTANT_DETAILS: "Important Details & Learning Preference ",
	IMPORTANT_DETAILS_TXT: "IMPORTANT_DETAILS",
	LEARNING_PREFERENCE: "LEARNING_PREFERENCE",
	ASPIRATIONS_TXT: "ASPIRATIONS",
	PROFESSIONAL_DEEP_DIVE: "PROFESSIONAL_DEEP_DIVE",
	AREA_OF_INTEREST_: "Area Of Interest",
	END_YR_BIG: "End year should be greater than start year",
	DUMMY_ABOUT:
		"I am a budding software developer and an enthusiastic reader. I have more than 4 years of experience in python coding. I love to connect to new people and learn new technologies. I am enthusiastic about cryptocurrency",
	DOUBT_TOOLTIP:
		"Please post your doubts here, your instructor will clarify these in the upcoming sessions",
	SELECT_MILESTONE: "Select Course",
	ENROLL_FOR_FREE: "Enroll for Free",
	LOG_OUT: "Logout",
	PROFILE: "Profile",
	FILTER_MILESTONES: "Filter Bookmarks by Courses",
	DELETE_BOOKMARK_MODAL: "Do you want to delete the bookmark?",
	BOOKMARK_NOT_FOUND: "Bookmarks not found !",
	NO_DOUBT: "Thereâ€™s no question, yet!",
	NO_SKILLS: "No Skills Listed",
	ADD_SKILLS: "Add your skills now.",
	NO_EDUCATION: "No Education Listed",
	NO_WORK_EXP: "No Work Experience listed!",
	NO_CERTIFICATE: "No Certificate listed!",
	NO_CERTIFICATE_DESC: "Include your certifications and qualifications",
	NO_INTEREST: "No Area of Interest Listed",
	ADD_INTEREST: "Add your area of interest here",
	NO_ABOUT: "Thereâ€™s no about listed!",
	PLZ_ADD_ABOUT: "Please Add About Section",
	NO_CAREER: "No Career Profile Listed",
	ADD_CAREER: "Add your career profile",
	BOOKMARK_DESC:
		"It seems that there are no bookmarks saved for this course at this time.",
	NO_DOUBT_DESC:
		"Please post your doubts here, your instructor will clarify these in the upcoming sessions",
	NOTES_NOT_FOUND: "Notes not found !",
	ADD_WORK_EXP: "Add your previous work experience",
	ADD_ABOUT: "Tell us more about yourself",
	ADD_PREV_EDUCATION: "Add your Education here.",
	ADD_CERTIFICATE: "Add your certificates",
	NOTES_DESC:
		"It seems that there are no notes saved for this course at this time.",
	PM: "PM",
	POST_YOUR_DOUBT: "Post your Doubt",
	EDIT_DOUBT_MODAL: "edit_doubt_modal",
	ASK_DOUBT_MODAL: "ask_a_doubt_modal",
	YET_TO_BE_CONFIRMED: "Yet to be Confirmed",
	YET_TO_START: "Yet to start",
	BUDDY_CONNECT: "Buddy Connect",
	MENTOR: "Mentor",
	SORT_BY: "Sort by",
	FILTER: "Filter",
	NOT_AVAILABLE: "Not Available",
	NOT_AVAILABLE_DESC:
		"No courses/programs assigned to you that needs additional profile information",
	ASK_A_DOUBT: "Ask a Doubt",
	COMPLETED: "Completed",
	MY_ACCOUNT: "My Account",
	MY_APPLICATIONS: "My Applications",
	APPLIED_JOBS: "Applied Jobs",
	ABROAD_DASHBOARD: "Abroad Dashboard",
	HELP_SUPPORT: "Help & Support",
	RAISE_A_TICKET: "Raise a ticket",
	RAISE_A_ISSUE: "Raise an issue",
	HELP_AND_SUPPORT: "Help and Support",
	STATUS: "Status",
	RESET: "Reset",
	APPLY: "Apply",
	NOT_EMPLOYED: "Not Currently Employed",
	AM: "AM",
	CAUGHT_UP_TXT: "You're all caught up",
	JOIN_SESSION_MSG: "You can join the session on",
	JOIN_SESSION_MSG_1: "on or after",
	RECORD_NOT_AVAIL: "Record not available",
	SESSION_START_INFO: "You can join the session 2 hrs prior to the session",
	COURSES: "Courses",
	MY_PROGRAMS: "My Programs",
	LIBRARY: "Library",
	CALENDAR: "Calendar",
	VIEW_ALL: "View all",
	ARE_YOU_SURE_YOU_WANT_TO_APPLY_FOR_RE_EVALUATION:
		"Are you sure you want to apply for re-evaluation?",
	VIEW: "View",
	OPEN: "Open",
	CLOSED: "Closed",
	UPCOMING: "Upcoming",
	ADDRESS: "Address",
	YETTOSTART: "Yet to Start",
	ENTER_ADDRESS: "Enter Your Address",
	UPCOMING_EVENTS: "Upcoming",
	PAST_EVENTS: "Past",
	VIEW_DETAIL: "View detail",
	VIDEO_NOT_FOUND: "Video Not Found",
	VIEW_DETAILS: "View Details",
	RAISE_TICKET: "Raise a new ticket",
	NO_QUERIES_FOUND: "No queries found!",
	NO_QUERIES_FOUND_DESC: "You haven't raised any queries yet",
	RAISE_DESC:
		"Our team will address any issues related to the course, connectivity, sessions, payments and more. Raise Issue",
	LIVE: "Live",
	LIVE_NOW: "Live Now",
	NO_EVENTS: "No Events Available",
	PLAY_RECORD: "Play Record",
	SUBMIT_ANYWAY: "Submit Anyway",
	NOT_VISITED: "Not Visited",
	CHECK_AGAIN: "Check Again",
	UNANSWERED: "Unanswered",
	PLEASE_REVIEW: "Please review your submission",
	SOME_QUESTIONS_UNATTEMPTED: "Some questions are unattempted",
	AUTO_SUBMIT_TEXT: "Your Assessment will be auto submitted",
	ATTEMPT_LEVEL: "question",
	NOT_ATTENDED: "Not-Attended",
	NOT_ATTENDED_WITHOUT: "Not Attended",
	TIMES_UP: "Oops! Time's up.",
	DOUBT: "Ask a Doubt",
	RECENT: "Recent",
	UPVOTES: "Upvotes",
	RE_SCHEDULE: "Re-schedule",
	RE_SCHEDULE_REQUIRED: "Re-schedule requested",
	CANCELLED: "Cancelled",
	ATTENDED: "Attended",
	TRAIL_EXPIRES: "trial_expired",
	HRS_PULES: "Hrs",
	LEARNER: "Learner",
	REFER_NOW: "Refer Now",
	FREE_TRIAL_ERROR: "Free Trial Error Popup has been closed",
	AVAILABLE: "Available",
	CONSUMED: "Consumed",
	REMAINING: "Remaining",
	ERROR: "Error!",
	LOCK_MODAL: "Lock Modal has been closed",
	TRY_AGAIN: "Try Again",
	TRIAL_EX: "Trial Expired",
	MENTORING_REMAINING: "Mentoring hours remaining",
	TRIAL_EXPIRED: "Your Trial has expired",
	CONGRATULATIONS: "Congratulations!",
	YOU_ARE_ENROLLED_TO: "You are enrolled to",
	SCHEDULE_A_SESSION: "Schedule a Session",
	NO_ATTEMPT: "No Attempt remaining",
	ASSET_UNLOCK_SUCCESS: "Asset Unlocked Successfully",
	ERROR_DESC: "Something went wrong. 	Please try again",
	CONFIRM_FOR_ENROLL: "Please confirm if you would like to enroll for",
	NETWORK_ISSUE_TITLE: "Network Lost!",
	NETWORK_LOST_TITLE: "Network Connection Lost",
	NETWORK_LOST_DESC:
		"This app needs an internet connection. Please reconnect to proceed.",
	OVERALL: "Overall",
	VIMEO_UNKNOWN_ERR_MSG:
		"That wasn't supposed to happen. Please try again in a few minutes.",
	COMPLIMENTARY: "Complimentary",
	LOGIN_FAILED: "Login Failed...Please try again.",
	LOG_OUT_FAILED: "Logout Failed...Please try again.",
	ERROR_WITH_VERIFY_OTP: "Error with verify OTP",
	VERIFIED_OTP: "OTP has been verified!",
	OTP_FAILED: "OTP Failed!",
	AUTH_SESSION_EXPIRED: "Session expired...Please login again",
	FEEDBACK: "Give your valuable feedback here",
	INCORRECT_OTP_MESSAGE: "Incorrect OTP",
	IMPROVE: "How can we improve our product?",
	YOUR_OPINION_MATTER: "Your opinion matters!",
	YOUR_FEEDBACK_DESC:
		"Your feedback is very important. Please take this 1 minute survey so we can serve you better in the coming days",
	SHARE_FEEDBACK: "Share Feedback",
	OPTIONAL: "(optional)",
	OPTIONAL_TXT: "Optional",
	DO_YOU_WANT_TO_DELETE_THE_NOTE: "Do you want to delete the note?",
	DELETE_DOUBT_HEADING: "Delete this Doubt?",
	DISCARD_CHANGES: "Discard changes?",
	REQ_DES: "Description is required",
	DELETE_DOUBT_DESCRIPTION:
		"All the data of this doubt will be permanently wiped from the system.",
	CHANGES_NOT_SAVED: "Changes youâ€™ve made wonâ€™t be saved",
	ABOUT_PLACEHOLDER: "Tell more about yourself",
	DELETE_TEXT: "Delete",
	DELETE_EDUCATION_DESCRIPTION:
		"Please confirm if you would like to delete this education?",
	THANKS_FEEDBACK: "Thanks! We value your feedback.",
	DELETE_EXPERIENCE_DESCRIPTION:
		"Please confirm if you would like to delete this experience?",
	NO_MORE_EXTENSION: `You will not be able to push the deadline any further. Only`,
	LEFT_FOR_SUBMISSION: "more such extensions are left for other submissions.",
	ON_CANCEL_ASSIGNMENT:
		"Without the extension, the submission must be completed by ",
	AVOID_PENALTY: "to prevent any penalties.",
	WHY_DEL: "Why are you deleting you account?",
	OFFLINE_MSG: "There is no internet. Please check your internet connection",
	DONE: "Done",
	SORRY_DESC:
		"Deleting your account will permanently remove all your data and cannot be undone. If you proceed, you will lose access to your courses, sessions, profile, order history, and any saved preferences.",
	SORRY: "We are sorry to see you go !",
	AVAILABLE_SLOT_DESC:
		"Clicking on date will show you all the available slots for that date.",
	AVAIL_SLOT_DESC: "Click on continue to view all available slots for",
	ACCOUNT_DELETE_SUCCESS_DES:
		"Weâ€™re sorry to see you go. To reactivate your \naccount drop an email to \nsupport@knowledgehut.com within 30 days.",
	SCHEDULE_SESSION: "Schedule a mentoring session for",
	SELECT_OPTION_FORM_ABOVE: "Please select option form above.",
	WENT_WRONG: "Something went wrong",
	MILESTONE: "Course",
	SCORE_RECORD:
		"Scores for evaluation components have not been published yet",
	WEIGHTAGE_TXT: "Weightage",
	NEED_ASSISTANCE: "Need assistance?",
	GO_AHEAD_TXT: "Go Ahead and Raise your first ticket!!",
	OPEN_STATE:
		"There are no Open tickets. Click on New Ticket to raise an issue.",
	CLOSED_STATE: "There are no closed tickets.",
	DELETE_BTN: "Delete Account",
	SETTINGS: "Settings",
	ASSESSMENTS: "Assessments",
	ASSIGNMENTS: "Assignments",
	PROJECTS: "Projects",
	DELETE_TXT: "Delete",
	HANDS_ON: "Hands-On",
	ADD_NOTE: "Add Note",
	SAVE_NOTE: "Save Note",
	JOIN_WHATSAPP: "Join Whatsapp",
	JOIN_TELEGRAM: "Join Telegram",
	SAVE: "SAVE",
	WELCOME: "Welcome! ðŸ‘‹",
	DELETE: "Delete your Account",
	ARE_YOU_SURE: "Are you sure?",
	COMPLETE_PROFILE: "Complete your profile",
	COMPLETE_PROFILE_DESC:
		"Enable better assistance by sharing your details with us!",
	IN_COMPLETE_PROFILE:
		"Sorry for the inconvenience. Complete details to continue learning",
	IN_COMPLETE_PROFILE_DESC:
		"The submission deadline has passed for the following sections. Please fill the details to resume learning.",
	FEEDBACK_SUBMITTED: "Feedback Submitted!",
	EXTENSION_TXT: "Are you sure you want to extend the Due Date?",
	CANCEL_EXTENSION_TXT:
		"Are you sure you want to cancel Extension of due date? ",
	RESEND_IN: "Resend OTP in ",
	RESEND_OTP: "Resend OTP",
	RESEND_OTP_IN: "Resend OTP in",
	OTP_VERIFICATION: "OTP Verification",
	UNLOCK_ASSET: "Unlock Asset",
	MY_COURSES: "My Courses",
	IN_PROGRESS: "In Progress",
	ONGOING_COURSES: "Ongoing Courses",
	COMPLETED_COURSES: "Completed Courses",
	RESULTS: "Results",
	SHOWING: "Showing",
	NO_RSULT: "No Result found",
	LOADING_SEARCH: "Loading Search Results",
	SET_TO_GO_LIVE: "Set to go Live",
	GET_STARTED: "Get Started",
	LOADING: "Loading...",
	PROFILE_PAGE: "Profile Page",
	EDIT_NOTE: "Edit Note",
	EDIT_DOUBT: "Edit your Doubt",
	EDIT: "Edit",
	SUBMIT: "Submit",
	DELETE_EDUCATION_TXT: "Delete Education",
	WRITE_REASON_HERE: "Write your reason here.",
	DELETE_EXPEDIENCE_TXT: "Delete Work Experience",
	NO_NOTE_FOUND: "Notes not found !",
	REPORT_SUBMIT_SUCCESS: "Report submitted successfully",
	HELP_US_IMPROVE: "Help us Improve!",
	WHAT_WENT_WRONG_TEXT: "Tell us what went wrong so we can serve you better.",
	REPORT_SUBMIT_FAILED:
		"Report not submitted, please try again after some time.",
	ADDITIONAL_INFO_SUCCESS: "Additional Information updated successfully",
	UNLOCK_ASSET_PLACEHOLDER:
		"Enter the reason for the delay in completing the asset",
	COURSE_NAME: "Course Name",
	SESSION_NAME: "Session Name",
	LIFE_TIME_ACCESS: "Life Time Access",
	CLEAR_FILTER: "Clear Filter",
	CATEGORY: "Category",
	ARTIFACT_LOCKED: "Artifact Locked !",
	COURSE_CATEGORY: "Course Category",
	NOTE_ADDED: "Note added successfully",
	GENERAL_NOTE_ADDED: "General Note added successfully",
	GENERAL_NOTE_UPDATED: "General Note updated successfully",
	GENERAL_NOTE_DELETE: "General Note deleted successfully",
	GENERAL_NOTE_HINT:
		"General Notes let you capture your thoughts that aren’t tied to a specific asset.",
	NOTE_DELETED: "Note deleted successfully",
	NO_NOTE_AVAILABLE: "No note available",
	NOTE_EDITED: "Note edited successfully",
	HEADING_CAN_BE_EMPTY: "Heading can not be empty.",
	FIELD_NOT_BE_EXCEED_CHARACTER:
		"This field should not exceed 80 characters.",
	FIELD_CAN_NOT_BE_EMPTY: "This field can not be empty. ",
	NOTE_CAN_BE_EMPTY: "Note can not be empty.",
	BOOKMARK_ADDED: "Bookmark added successfully",
	DUE_DATE_EXTENDED_SUCCESSFULLY: "Due date has been extended successfully",
	CANCELLED_EXTENDED_SUCCESSFULLY:
		"Due date extension has been cancelled successfully",
	BOOKMARK_DELETED: "Bookmark removed successfully",
	CURRENT_COURSE_NOT_FOUND: "Current Course not found",
	USER_NOT_FOUND: "Email id not registered with us",
	TOKEN_EXPIRED_ERROR: "Your token has expired. Please re-login to continue.",
	ABOUT_UPDATED: "About Updated Successfully",
	ABOUT_ADDED: "About Added Successfully",
	ABOUT_INSTRUCTOR: "About Instructor",
	ACCOUNT_UPDATED: "Account Updated Successfully",
	EXPERIENCE_DELETED_MESSAGE: "Experience Deleted Successfully",
	ARTIFACT_UNLOCK:
		"Some of the learning artifacts currently locked are due to be unlocked on",
	CONTACT: "Contact ",
	DELETE_EDUCATION: "Education deleted successfully",
	NO_EDUCATION_DATA: "Please fill all fields!",
	UPDATE_EDUCATION: "Education updated successfully",
	ADD_EDUCATION: "Education added successfully",
	POST_DOUBT: "Your Doubt has been posted",
	YOUR_BACK_MESSAGE: "Your account is back!",
	DELETE_DOUBT: "Your Doubt has been deleted",
	CHANGES_SAVED: "Changes Saved",
	DEGREE: "Degree",
	COLLEGE: "College/University/School",
	CONTACT_DESC: "should you require assistance.",
	ASSET_UNLOCK_TIME_PASSED: "Time to unlock learning artifacts has passed",
	ASSET_UNLOCK_TIME_PASSED_DESC:
		"Some of the learning artifacts can be unlocked only within the stipulated time.",
	NOTE_PLACEHOLDER: "Enter your note here",
	DOUBT_PLACEHOLDER: "Enter your doubt here",
	ENTER_MESSAGE: "Enter a message",
	NO_PERMISSION: "No enough permission to perform the action",
	LOG_OUT_DESC: "Are you sure  you want to logout?",
	UNLOCK_ATTEMPT_TITLE: "unlock attempts remaining!",
	CHOOSE_FILE_BELOW_10MB: "Please choose a file below 10 mb",
	CHOOSE_FILE_BELOW_50MB: "Please choose a file below 50 mb",
	UNLOCK_ATTEMPT_DESC:
		"Use unlock attempt to unlock the asset. Please contact your learning advisor for more information.",
	ATTEMPTS_EXHAUSTED_DESC:
		"You have exhausted all your attempts. Please raise a ticket to know more",
	ARTIFACT_LOCKED_DESC:
		"Please complete your previous asset to unlock this asset!",
	ARTIFACT_NOT_UNLOCKED_TITLE: "Learning artifacts yet to be unlocked!",
	ARTIFACT_UNLOCK_TITLE: "unlock attempts remaining!",
	START_QUIZ: "Start Quiz",
	RESUME_QUIZ: "Resume Quiz",
	ARTIFACT_UNLOCK_DESC:
		"Use unlock attempt to unlock the asset. The unlocked assets needs to be completed within two days of unlocking.",
	ARTIFACT_ACCESS_DESKTOP_DESC:
		"This asset can only be accessed on desktop. Please visit PRISM on a computer to view this asset.",
	ARTIFACT_ATTEMPT_EXPIRED:
		"You have exhausted your 3 unlock limits. Please contact your learning advisor.",
	COURSE_ACCESS_DESKTOP_DESC:
		"This course can only be accessed on desktop. Please visit PRISM on a computer to view this course.",
	DAILY_STREAK: "Daily Streak",
	SUCCESSFULLY_LOGGED_IN: "Successfully logged in.",
	LOG_IN_WITH: "Or Login with",
	CONTACT_ADVISOR: "Please contact your learning advisor.",
	JOIN_MEETING: "Join Meeting",
	EVENTS: "Events",
	DOUBT_FORM: "Doubt Form",
	NEW_EVENTS: "Upcoming Events",
	EXPLORE_MORE: "Explore More",
	VIEW_CALENDAR: "View Calendar",
	LEFT_TO_ASK: " Left to Ask",
	LIFETIME_COURSE: "Paid",
	TIME_ZONE: "Time Zone",
	ACCESS_EXPIRED: "Access Expired",
	ACCESS_ENDS_IN_DAYS: (days: number) => `Access ends in ${days} days`,
	ACCESS_ENDS_IN_HOURS: (hours: number) => `Access ends in ${hours} hours`,
	ACCESS_ENDS_IN_DAYS_HOURS: (days: number, hours: number) =>
		`Access ends in ${days} days ${hours} hours`,
	OTP_SEND: "Weâ€™ve sent an OTP to ",
	THIS_FIELD_IS_REQUIRED: "This field is required.",
	DESCRIPTION_REQUIRED: "Description is required",
	COURSE_REQUIRED: "Course is required",
	CHAR_LIMIT_ALLOWED: "at most 300 chars allowed",
	CHARACTER: "Character",
	CATEGORY_REQUIRED: "Category is required",
	SUBJECT_REQUIRED: "Subject is required",
	EXPLORE_COURSES: "Explore Courses",
	ENTER_MOB: "Enter Your Phone Number",
	EXPIRING_DESC_2: " Rs.20,000 PRISM ",
	OTP_RESEND_DESC: "Didn't receive OTP?",
	EXPIRING_DESC_1: "Two days to go before",
	EXPIRED_DESC_2: " Full Stack Development ",
	END_OF_LIB: "Your are at end of the list !",
	EXPIRED_DESC_3: "course and resume learning.",
	NOT_VALID_EMAIL: "Email is not valid.",
	NOT_VALID_ID: "Please enter valid id",
	NO_COURSES: "There are no Courses to display!!",
	PERSONAL_DETAILS: "Personal Details",
	NO_DATE_ERR: "Please choose a date to continue",
	NOT_VALID_MOB: "Phone number is not valid.",
	DOWNLOAD_ZIP_SUCCESS: "Zip downloaded successfully",
	DOWNLOAD_NOTES_SUCCESS: "Note(s) downloaded successfully",
	DOWNLOAD_SUCCESS: "File downloaded successfully",
	DOWNLOAD_FAILED: "File download failed...Please try again",
	NO_MENTOR_HOURS: "No mentoring hours left",
	DOWNLOAD_CERTIFICATE_SUCCESS: "Certificate downloaded successfully",
	DOWNLOAD_CERTIFICATE_FAIL:
		"Certificates download failed...Please try again",
	ENTER_CREDENTIALS: "Enter your phone number or email",
	NO__NEW_EVENTS_DESC: "There are no upcoming eventsðŸ˜•",
	FREE_TRIAL_EXPIRED: "Oh no! Your FREE Trial has ended!",
	FREE_TRIAL_EXPIRING: "You free trial is expiring soon!",
	STORAGE_PERMISSION_TITLE: "Storage Permission Required",
	NO_COURSES_DESC: "Try changing the filter & search again",
	MENTOR_NOT_AVAIL: "Mentor not available on selected slots",
	DOWNLOAD_ZIP_FAIL: "Zip downloaded failed...Please try again",
	DOWNLOAD_NOTE_FAIL: "Note(s) download failed...Please try again",
	EXPIRED_DESC_1: "But your learning journey can continue. Purchase the",
	EXPLORE_LIB_DESC: "Explore more courses to move up the career ladder.",
	LOG_IN_DESC: "Login or Signup to kickstart your immersive learning journey",
	STORAGE_PERMISSION_DESC:
		"Application needs access to your storage to download File",
	EXPLORE_COURSE_DESC:
		"Start Building In-Demand Tech Skills and Land a Software Dev Job",
	EXPIRING_DESC_3:
		"Cash expires. Complete the remaining sessions to claim the benefits.",
	DAILY_STREAK_DESC:
		"To accomplish daily streak, complete a learning exercise or make a note.",
	SEARCH_HERE: "Search here",
	SEARCH: "Search",
	BLENDED: "Blended",
	PLZ_CLICK_HERE:
		"has been evaluated. Please click on view report to see details.",
	SUCCESSFULLY_SUBMITTED: "You have successfully submitted the",
	UNDER_REVIEW:
		"It is under review and you will be notified once evaluation is complete.",
	SUBMISSION_UNDER_REVIEW:
		"Submission under Review. Go to Desktop to check status.",
	FOR_RE_EVALUATION: "for re-evaluation on",
	SHARE: "SHARE",
	DOWNLOAD: "Download",
	KEEP_MY_ACCOUNT: "Keep My account",
	REQUEST_RESCHEDULE_DESC: "requested to reschedule this session to",
	DOWNLOADING: "Downloading...",
	ENTER_OTP: "Enter OTP",
	CONFIRM_RESCHEDULE: "Confirm re-schedule",
	ATTACHMENT_SIZE_NEEDS_TO_BE_LESS_THAN_20_MB:
		"Attachment size needs to be less than 20 mb",
	ACCOUNT_DELETE_OTP_DES:
		"Your account will be deleted. After that you wonâ€™t be able to log into your account. To reactivate your account drop an email to support@knowledgehut.com within 30 days.",
	REGISTER_EMAIL_OTP:
		"To verify itâ€™s you, enter the OTP received on your registered email.",
	DOWNLOAD_ALL_NOTES: "Download all Notes",
	COURSE_LIBRARY: "Course Library",
	NO_NOTS_FOUND_DES:
		"It seems that there are no notes saved \n for this course at this time.",
	FREE_COURSE: "Free Course",
	GITHUB_PROFILE: "Github Profile",
	STACK_PROFILE: "Stackoverflow Profile",
	DESCRIPTION:
		"Click Code and copy the HTTPS link. Now open RStudio, click File/ New Project/ Version control/ Git and paste the HTTPS link from the Github repository into the Repository URL: field. Select a folder on your computer - that is where the â€œlocalâ€ copy of your repository will be (the online one being on Github).",
	READ_MORE: "Read More",
	ELEVATE: "Big Surprises Await You",
	ELEVATE_DESC:
		"We've been working hard to deliver a host of game-changing functionalities. Brace yourself for an enhanced app experience like never before!",
	READ_LESS: "Read Less",
	FREE_TRIAL_BANNER: "Free Trial",
	DAYS_LEFT: "Days left",
	CONTENT:
		"Click Code and copy the HTTPS link. Now open RStudio, click File/ New link. Now open RStudio, click File/ New Project/ Version control/ Git and paste the HTTPS link from the Github repository into the Repository URL: field. Select a folder on your computer - that is where the â€œlocalâ€ copy of your repository will be (the online one being on Github)",
	TITLE: "Web Development",
	MILESTONES: "Courses",
	RECALL_QUIZ: "Recall Quiz",
	RECORD_UN_AVAIL:
		"The recorded video of the session is being processed. It will be available shortly.",
	TRIAL: "trial",
	NO_EMAIL: "Email not found",
	PHONE_NUMBER_NOT_REGISTERED: "Phone number is not registered.",
	MAXIMUM_ATTEMPT_REACHED:
		"Retry limit exceeded. Please try again after 10 minutes.",
	EMAIL_NOT_REGISTERED: "Email is not registered.",
	INSTRUCTIONS: "Instructions",
	DESCRIPTIONS_QUIZ: "Description",
	FREE_TRIAL: "Your Free Trial has expired",
	TRIAL_END: "Oops! Access to this course has expired",
	TRIAL_END_DESC:
		"Your access to this course has expired. To extend your access, please click on the button below to contact support. Raise a ticket, and weâ€™ll get back to you!",
	FREE_TRIAL_DESCRIPTION:
		"You're free trial period has expired. Purchased the course to unlock all the features (assessment cloud labs, much more) and have an awesome immersive learning experience.",
	UPGRADE_NOW: "Upgrade Now",
	LOCKED: "Item's Locked",
	LOCKED_DESCRIPTION:
		"Oops! This portion of PRISM is available with the full subscription only. Upgrade to the full FSD BootCamp now and get more out of your learning.",
	FREE_EXPIRED: "Free Trial Expired",
	FREE_TRIAL_UPGRADE: "Upgrade for better learning experience",
	UPGRADE: "Upgrade",
	MORE_INFO: "More Info",
	BOOKMARKS: "Bookmarks",
	GENERAL_NOTES: "General Notes",
	SESSION: "Session",
	FREE_TRIAL_TITLE:
		"Your Free Trial for Full Stack Development BootCamp has begun.",
	FREE_TRAIL_DAYS: "You can access the course for \n the next 14 days.",
	START_LEARNING: "Start Learning",
	HI: "Hi",
	MULTI_CORRECT_ANSWER:
		"Good Job! You got it right, please check for the reason below",
	YOUR_ACCOUNT_HAS_BEEN_DELETED: "Your account has been  deleted ðŸ˜•",
	MULTI_WRONG_ANSWER:
		"Sorry, but you have got it wrong, please check for the reason below",
	REVISE_COURSE: "Revise Course",
	REVISE: "Revisit",
	ADD_NOTES: "Add Notes",
	NOTES: "Notes",
	NOTE: "Note :",
	DUE: "Due",
	CAREER_PROFILE: "Career Profile",
	ADDITIONAL_INFO: "Additional Information",
	ADDITIONAL_INFO_PROFILE: "Programs that require additional Information",
	DUE_DATE: "Due Date",
	NEW_DUE_DATE: "Extended Due Date",
	AVAILABLE_FROM: "Available from",
	NEED_EXTENSION: "Need Extension",
	CANCEL_EXTENSION: "Cancel Extension",
	JOIN_COMMUNITY_HEADER_TEXT: "Join our community & get access to",
	REPORT: "Report",
	START_AT: "Starts At",
	ASSET_ISSUE: "Learning Asset Issue",
	NOT_SUPPORT_DEC:
		"This asset can only be accessed on desktop. Please visit PRISM on a computer to view this asset.",
	KH_URL: "https://www.upgrad.com/",
	SS_FAIL: "Un-able to take screen shot...Please try again later",
	QUESTION_SKIP:
		"This question is not supported in Mobile at this point of time",
	GET_STARTED_FREE: "Get started with our free courses",
	WELCOME_FREE_USER_MESSAGE:
		"Here are some free courses for you to get started!",
	MORE_YOU_REFER_MORE_YOU_EARN: "More you refer -  More you earn!",
	YOUR_REFERRAL_CODE_IS: "Your Referral Code is:",
	REFERRAL_DESCRIPTION_TEXT_1: "Refer today & Change your world.",
	REFERRAL_DESCRIPTION_TEXT_2:
		"Get your friends to level up their skills and you could win exciting rewards like",
	REFERRAL_DESCRIPTION_TEXT_3:
		" MacBook Air, iPhone 14, iPad, Apple Watch, cashback offers,",
	REFERRAL_DESCRIPTION_TEXT_4: " or exclusive discounts of up to",
	REFERRAL_DESCRIPTION_TEXT_5: " 50%",
	REFERRAL_DESCRIPTION_TEXT_6: " on your program fees",
	REFER_EARN: "Refer & Earn",
	PROGRAM: "Program",
	JOIN_THE_COMMUNITY: "Join The Community",
	NOT_ABLE_TO_SEEK: "Watch the video once to seek forward",
	ALL: "All",
	FREE_COURSES: "Free Courses",
	SELECT_A_SLOT_ON: "Select a slot on",
	UPDATE_PROFILE_PICTURE: "Update Profile Picture",
	VIEW_PROFILE_PICTURE: "View Profile Picture",
	CONFIRM: "Confirm",
	TYPE: "Type",
	GET_EXTENSION: "Get Extension ",
	TYPE_HERE: "Type here",
	SELECT_A_SLOT_TO_CONTINUE: "Select a slot to continue",
	CONTENT_IS_NOT_LOADING: "Content is not loading / working",
	OVERALL_CONTENT_SHOWN_IN_THE_ASSET_IS_INCORRECT:
		"Overall content in the asset is incorrect/ irrelevant",
	QUIZ_CONTENT_IS_IRRELEVANT:
		"Quiz(s) content in the asset is incorrect/ irrelevant.",
	VIDEO_CONTENT_IS_OUTDATED:
		"Video content in the asset is incorrect/ irrelevant.",
	IMAGE_CONTENT_IS_OUTDATED:
		"Image content in the asset is incorrect/ irrelevant.",
	SLOTS_AVAILABLE: "Slots Available",
	SESSION_BOOKED: "Session booked",
	CONFIRM_RE_SCHEDULE: "Re- Schedule Confirmed",
	FILTER_BY_MILESTONE: "Filter Notes by Courses",
	WHAT_TYPE_OF_ISSUE_ARE_YOU_REPORTING:
		"What type of issue are you reporting?",
	EXPLAIN_YOUR_ISSUE: "Explain your issue here",
	ATTACH_SCREENSHOT: "Attach Screenshot",
	REPORT_AN_ISSUE_ON: "Report an issue on:",
	NO_SLOT_AVAILABLE_YET: "No slot available, yet!",
	NO_SESSION: "No sessions available on selected date",
	MENTOR_NOT_MARKED_DESC:
		"Your mentor hasnâ€™t marked any available slot on this day, please comeback later.",
	YOU_BOOKED_A_MENTORING_SESSION_ON: "You've booked a mentoring session on",
	RE_SCHEDULE_CONFIRM_DESC: "Youâ€™ve confirmed a mentoring session on",
	DOB: "Date of Birth",
	GENDER: "Gender",
	NOT_ASSIGNED: "N/A",
	CITY: "City",
	STATE: "State",
	DREAM_ROLE: "Dream Role",
	DREAM_COMPANY: "Dream Company",
	DREAM_ROLE_EXP_DESC: "Experience Matching your Dream Role",
	RELEVANT_EXP: "Relevant Experience",
	IS_WORKING: "Is Working",
	ORGANIZATION_TXT: "Organization",
	CODING_REQUIRED_TXT: "Coding Required",
	EXPERIENCE_TXT: "Experience",
	INDUSTRY_TXT: "Industry",
	PRESENT: "Present",
	DESIGNATION_TXT: "Designation",
	NATIONALITY: "Nationality",
	COUNTRY_TXT: "Country",
	STATE_TXT: "State",
	COUNTRY_OF_RESIDENCE: "Country of Residence",
	TIMEZONE: "Timezone",
	LINKEDIN_PRO: "LinkedIn Profile",
	UPLOAD_RESUME: "Upload Resume",
	DATE_OF_BIRTH: "Date of Birth",
	ALTERNATE_EMAIL: "Alternate Email Id",
	EMAIL_ID: "Email Id",
	MAX_LIMIT_REACHED_RESUME:
		"You can keep up to 6 resumes. Delete one to upload a new one.",
	RESUME_LIMIT_TEXT: "You can upload upto 6 resume(s)",
	RESUME_UPLOAD_SIZE:
		"Preferred formats: PDF, DOCX or DOC with maximum file size upto 3 MB.",
	VIDEO_RESUME_URL: "Video Resume URL",
	VIDEO_RESUME_URL_PLACEHOLDER: "Add URLs from Google Drive, OneDrive etc.",
	ENSURE_URL_DESC: "Ensure the link you're sharing is publicly accessible.",
	VIDEO_RESUME_UPLOAD_FORMAT:
		"Preferred format: MP4 with a max file size upto 50MB. You can upload only ONE file",
	RESUME_UPLOAD_FORMAT:
		"Preferred formats: PDF, DOCX or DOC with maximum file size upto 10 MB. You can upload one file at a time.",
	ENTER_URL: "Enter URL",
	UPLOAD_HERE: "Upload here",
	UPLOAD_VIDEO_RESUME: "Upload Video Resume",
	SELECT_DATE: "Select Date",
	SELECT_YEAR: "Select Year",
	START_DATE: "Start Date",
	START_YEAR: "Start Year",
	START_ASSESSMENT: "Start Assessment",
	NO_ATTEMPT_AVAILABLE: "No Attempt Available",
	ATTEMPT_LEFT_UNLIMITED: "Unlimited Attempts Left",
	RETAKE_ASSESSMENT: "Retake Assessment",
	RETAKE_ASSESSMENT_POST_SUBMISSION: "Re-Take Assessment",
	RESUME_ASSESSMENT: "Resume Assessment",
	END_YEAR: "End Year",
	END_DATE: "End Date",
	PERCENTAGE: "Percentage",
	WORK_MODE: "Work Mode",
	JOB_LOC: "Job Location",
	NOTICE_PERIOD: "Notice Period",
	ADD_EDUCATION_DESCRIPTION:
		"Mention only the percentage number without the symbol. Convert CGPA to percentage by multiplying it with 9.5 Ex: if your CGPA is 8.32 = 8.32*9.5 = 79.04 If you are student, enter your GPA till now.",
	CURRENT_DESIGNATION: "Current Designation",
	CURRENT_DESIGNATION_DESCRIPTION:
		"If you are a fresher or you are currently not working please select â€˜Not-workingâ€™ or â€˜Self- Employedâ€™",
	CURRENT_ORGANIZATION: "Current Organization",
	CURRENT_ORGANIZATION_DESCRIPTION:
		"If you are a fresher or you are currently not working please select â€˜Not Workingâ€™ or â€˜Self Employedâ€™",
	CURRENT_CTC: "Current CTC",
	EXPECTED_CTC: "Expected CTC",
	EXPECTED_CTC_DESC:
		"If you are a fresher or you are currently not working please select â€˜Not-workingâ€™ or â€˜Self- Employedâ€™",
	CURRENT_CTC_DESC:
		"If you are a fresher or you are currently not working please select â€˜Not-workingâ€™ or â€˜Self- Employedâ€™",
	ARE_YOU_CURRENTLY_WORKING: "Are you currently working?",
	TOTAL_WORK_EXPERIENCE_IN_YEARS: "Total work experience (in Years)",
	TOTAL_WORK_EXPERIENCE_IN_YEARS_DESCRIPTION:
		"Only consider full time experiences, Freshers please select 0.",
	INDUSTRY: "Industry",
	I_AM_CURRENTLY_IN_THIS_ROLE: "I am currently in this role.",
	SELECT: "Select",
	SESSION_LINK_UN_AVAIL:
		"Session link is not available..Please try again later",
	DOES_YOUR_JOB_REQUIRE_CODING: "Does your job require coding?",
	NEVER: "Never",
	OCCASIONALLY: "Occasionally",
	DAILY: "Daily",
	INDUSTRY_DESCRIPTION: "Choose the closest match",
	ALL_COURSE: "All Courses",
	NOT_VALID_DATE: "Not a valid date",
	START_DATE_END_DATE_ERROR: "End Date should be greater than Start Date.",
	NO_DATA: "No Data",
	NA: "NA",
	EXPERIENCE_ADDED_MESSAGE: "Experience added successfully",
	EXPERIENCE_UPDATED_MESSAGE: "Experience updated successfully",
	ADD_ON_BOARDING_ITEM_MESSAGE:
		"Your desired option is not present in the list?, Please, add it!",
	APP_NOT_FOUND_MESSAGE:
		"File cannot be viewed. Please download a compatible app from your device's app store.",
	SELECT_COURSE_PROGRAM: "Select Course/Program",
	SELECT_CATEGORY: "Select Category",
	SELECT_SUBJECT: "Select Subject",
	DESCRIPTION_ONLY: "Description",
	ADD_ATTACHMENT: "Add Attachment",
	NEW_TICKET_CREATED_SUCCESSFULLY: "New ticket created successfully",
	SUBJECT: "Subject",
	WEEK_LOCKED: "This module is locked",
	UPLOADING: "Uploading",
	SELECT_SKILL: "Select your skills",
	ON_NOTICE_PERIOD: "On notice period?",
	WHATSAPP_NUMBER: "This is also my whatsapp number",
	CURRENT_DOMAIN: "Current Domain",
	SEARCH_DOMAIN: "Search Domain",
	DOMAIN_REQUIRED: "Domain is required",
	CLASS_12TH_BOARD: "Class 12th Board",
	CLASS_10TH_BOARD: "Class 10th Board",
	ACADEMIC_STREAM_CHOSEN: "Academic Stream Chosen",
	STREAM_CHOSEN: "Academic Stream",
	GRADUATION_YEAR_FROM: "Graduation Year From",
	GRADUATION_YEAR_TO: "Graduation Year To",
	PASSING_YEAR: "Passing Year",
	CLASS_10TH_SCHOOL_NAME: "Class 10th School Name",
	CLASS_12TH_SCHOOL_NAME: "Class 12th School Name",
	STREAM_IS_REQUIRED: "Stream is required",
	CLASS_12TH_BOARD_IS_REQUIRED: "Class 12th Board is required",
	CLASS_10TH_BOARD_IS_REQUIRED: "Class 10th Board is required",
	NAME_OF_THE_CERTIFICATION: "Name of the Certification",
	ISSUING_AUTHORITY: "Issuing Authority",
	ISSUE_DATE: "Issue Date",
	EXPIRATION_DATE: "Expiration Date",
	DOES_NOT_EXPIRE: "Does not expire",
	UPLOAD_CERTIFICATE: "Upload Certificate",
	UPLOAD_CERTIFICATE_REQUIREMENTS: "PDF (Preferred), PNG upto 5MB",
	ADD_CREDENTIAL_ID: "Add Credential ID",
	Add_CREDENTIAL_URL: "Add Credential URL",
	SKILLS_REQUIREMENT:
		"Associate at least 1 skill to this license or certification. It'll also appear in your skills section",
	ENTER_HERE: "Enter Here",
	SKILLS_UPDATED: "Skills updated",
	CERTIFICATE_ADDED: "Certification Added",
	UPDATE_CERTIFICATE: "Certification Updated",
	INVALID_URL: "Enter a valid link",
	UPLOAD_ASSIGNMENT: "Upload Assignment",
	UPLOAD_PROJECT: "Upload Project",
	START_ASSIGNMENT: "Start Assignment",
	START_PROJECT: "Start Project",
	SUBMIT_ASSESSMENT_CONFIRMATION:
		"Are you sure  you want to submit assignment?",
	KNOW_MORE: "Know More",
	AGENDA: "Agenda",
	SUBMIT_PROJECT_CONFIRMATION: "Are you sure  you want to submit project?",
	SUBMIT_CONFIRMATION: "Are you sure you want to submit ?",
	REMOVE_FILE_CONFIRMATION:
		"Are you sure  you want to remove the attachment?",
	TO_PASS: "to Pass",
	MINS_LEARNING: "Mins learning",
	SUBMIT_BY_DAYS: "Submit By Days",
	MAX: "Max",
	MARKS: "Marks",
	DURATION: "Duration",
	MAX_FILE_SIZE_50_MB: "\n• Max file size is 50 MB",
	MAX_FILE_SIZE_500_MB:
		"\n• Max file size is 500 MB for video files and 50 MB for non-video files",
	UPLOAD_ONLY: ", Upload only",
	FILE: "file",
	SUBMIT_ASSIGNMENT: "Submit Assignment",
	SUBMIT_PROJECT: "Submit Project",
	SUB_SKILLS: "Sub Skills:",
	REMOVE_ATTACHMENT: "Remove Attachment",
	SUBMITTED_ASSIGNMENT_TEMPLATE_ONE:
		"You have successfully submitted the assignment on",
	SUBMITTED_PROJECT_TEMPLATE_ONE:
		"You have successfully submitted the project on",
	SUBMITTED_ASSIGNMENT_TEMPLATE_TWO:
		"It is under review and you will be notified once evaluation is complete.",
	TIME_TAKEN_TO_COMPLETE:
		"How many minutes did you take to complete the sessions ?",
	TIME_TAKEN_TO_COMPLETE_PLACEHOLDER: "120 Mins",
	RATE_MODULE: "How would you rate this session ?",
	LEAVE_COMMENT: "Leave a comment:",
	LEAVE_COMMENT_PLACEHOLDER: "We would love to hear more from you",
	WHAT_WENT_WELL: "What went well?",
	WHAT_WENT_WRONG: "What went wrong?",
	HEY: "Hey",
	UNDERSTANDING_SCORE_CARD: "Understanding Score Card",
	HOW_IS_OVERALL: "How is overall program percentage calculated?Â ",
	CALCULATION:
		"Calculation of overall percentage in academic programs is essential for evaluating student performance considering the weighted percentages assigned to courses and the various graded components within them.",
	COMPONENTS: "Components of Overall Percentage Calculation",
	WEIGHTAGE: "Weightage of Courses: ",
	EACH_COURSE:
		"Each course in the program contributes to the overall percentage with a certain weightage, indicating its relative importance.\n",
	GRADED: "Graded Components within Courses: ",
	COURSES_COSIST:
		"Courses consist of various graded components such as assessments, assignments, projects, and other relevant tasks. These components contribute to the overall course grade and subsequently affect the overall percentage. Their significance may vary depending on their importance in assessing learning outcomes.\n",
	WEIGHTED: "Weighted Scores of Components: ",
	SCORES_OBTAINED:
		"Scores obtained in each component are weighted based on their contribution to the overall course grade. Weighted percentages are assigned to each component, reflecting its significance in evaluating student performance. Components with higher weightages have a greater impact on the overall course grade.\n",
	CALCULATION_PROCESS: "Calculation Process",
	WEIGHTED_CONTRIBUTION: "Weighted Contribution of Components: ",
	SCORES_OBTAINED_MUL:
		"Scores obtained in each component are multiplied by their respective weighted percentages to calculate their weighted contributions.\n\nThe weighted scores of all components within a course are summed to obtain the total weighted score for that course. This reflects the overall performance of the student in the course considering the varied contributions of its components.\n",

	CALCULATION_OF_COURSE: "Calculation of Course performance: ",
	SCORES_OF_STUDENT:
		"Scores of student's achievement in the course, considers both the performance in individual components and their weighted contributions.\n\nScores obtained in all courses are aggregated, considering their respective weightages to calculate the overall percentage of all courses in the program.\n",
	TOTAL_PROGRAM_PERCENTAGE: "Total Program Percentage Calculation: ",
	THE_TOTAL_PROGRAM_PERCENTAGE:
		"The total program percentage is derived from the scores obtained in each course, considering their defined percentage contribution to the overall program. Courses with higher weightages or defined percentages have a more significant impact on the total program percentage. The scaled scores of all courses are aggregated to obtain the total program score, which is then converted into a percentage. This method ensures a comprehensive assessment of the student's academic achievements throughout the program duration.",
	GIVE_OPINION: "Give Opinion",
	MIN_WORDS: "Min word limit 150 & Max 400",
	ENTER_YOUR_RESPONSE: "Enter your response here",
	ALL_RESPONSES: "All Responses",
	CLASS_OPINION: "Class Opinion",
	OPINION_SAVE: "Opinion added successfully",
	OPINION_UPDATE: "Opinion updated successfully",
	test: "Suppose you work as an engineer in a luxury mattress company. you are currently working on upgading a smart mattress to help people with sleeping disorders. you have 3 years of uer Aâ€™s heart rate recorded during sleep every night when using the old smaer mattress. the below shows the distribution of the heart rate of user A.",
	YOUR_SCORE: "Your Score",
	EVALUATION_CRITERIA: "Evaluation Criteria",
	EVALUATION_CRITERIA_DESCRIPTION:
		"This evaluation has been evaluated based on certain guidelines.",
	OVERALL_FEEDBACK: "Overall Feedback",
	WAS_THIS_HELPFUL: "Was this helpful for you?",
	RATE_YOUR_FEEDBACK: "Rate your submission feedback",
	FEEDBACK_REQUIRED: "Feedback required",
	VIEW_REPORT: "View Report",
	RESUBMIT_PROJECT: "Resubmit Project",
	RESUBMIT_ASSIGNMENT: "Resubmit Assignment",
	REMOVE_EXTRA_FILES: "Remove extra files",
	GRADING_DELAYED: "Grading was delayed",
	FILES: "files",
	VIEW_REEVALUATION_REPORT: "View  Re-evaluation Report",
	EVALUATION_CRITERIA_UNCLEAR: "Evaluation criteria is unclear",
	FEEDBACK_MORE_DETAILED: "Feedback should be more detailed",
	PROBLEM_STATEMENT_AMBIGUOUS: "Problem statement(s) were ambiguous",
	NO_EXTENSIONS_MESSAGE: "No more extensions available on submissions.",
	ARE_AVAILABLE_ACROSS_ALL_YOUR_SUBMISSION_OF_THIS_PROGRAM:
		"are available across all your submission of this program",

	HOME_REFER_AND_EARN: "Refer and Earn Exciting Rewards",
	HOME_REFER_AND_EARN_DESC:
		"Help a friend become an upGrad learner and earn rewards up to Rs 80,000.* #FriendshipGoals",

	HOME_EXPLORE_COURSES: "Struggling to find the right course?",
	HOME_EXPLORE_COURSES_CTA: "Explore",
	HOME_EXPLORE_COURSES_WEBVIEW: "Explore Courses",

	BE_THE_FIRST_ONE_TO_RESPOND: "Be the first one to respond",
	TAP_TO_PLAY: "Tap to Play",
	TAP_TO_PAUSE: "Tap to Pause",
	PROJECT_EVALUATED:
		"Your project has been evaluated. Please click on view report to see details.",
	ASSIGNMENT_EVALUATED:
		"Your Assignment has been evaluated. Please click on view report to see details.",
	PROJECT_EVALUATED_VIEW_REPORTS_PRISM_DESKTOP:
		"Your project has been evaluated. To view your reports, please visit Prism on a desktop computer.",
	ASSIGNMENT_EVALUATED_VIEW_REPORTS_PRISM_DESKTOP:
		"Your Assignment has been evaluated. To view your reports, please visit Prism on a desktop computer.",
	SURVEY: "Survey",
	ARE_YOU_SURE_YOU_WANT_TO_APPLY_FOR_THE_RE_EVALUATION_PROCESS:
		"Are you sure you want to apply for the re-evaluation process ?",
	RE_EVALUATION: "Re-evaluation",
	RE_EVALUATION_REQUEST:
		"Re-evaluation: Re-evaluation request will be accepted till",
	MIN_10_CHARACTERS_REQUIRED: "Min 10 characters required",
	THIS_IS_AN_INDICATIVE_DATE_RANGE_ONLY:
		"*This is an indicative date range only",
	SUBMIT_FOR_RE_EVALUATION: "Submit for Re-evaluation",
	TAKE_OUT_FEW:
		"Take out few minutes to fill the survey and continue learning.",
	REVALUATION_ASSIGNMENT_COMPLETED:
		"Your assignment has been evaluated. Please click on view re-evaluation report to see details.",
	REVALUATION_PROJECT_COMPLETED:
		"Your project has been evaluated. Please click on view re-evaluation report to see details.",
	VIEW_REVALUTION_REPORT: "View Re-evaluation Report",
	QUESTION_IS_INCORRECT: "Question is incorrect",
	ANSWER_OPTION_IS_UNRESPONSIVE: "Answer option is unresponsive",
	CORRECT_ANSWER_OPTION_IS_UNAVAILABLE:
		"Correct answer option is unavailable",
	OTHER: "Other",
	MAI_ASK: "mAI-ask",
	SKILLED_SCORE_RECORD:
		"To view your skill reports, please visit Prism on a desktop computer.",
	NOT_COMPLETED_DES:
		"You need to complete the previous learning resource before accessing this one.",
	GO_BACK_TO_STUDY_PLAN: "Go back to Study Plan",
	LECTURE: "Lecture",
	NEXT_UP: "Next Up",
	JOIN_NOW: "Join Now",
	TECHNICAL_ERROR: "Technical Error",
	OVERALL_CONTENT_ERROR: "Overall Content Error",
	UPGRAD: "upGrad",
	DISMISS: "Dismiss",
	ACCESS_ASSET_LOCKED: "Access to learning artifacts locked",
	VIEW_ON_DESKTOP: "View on Desktop",
	VIEW_ON_DESKTOP_DESCRIPTION:
		"The detailed report for the result is not supported on mobile devices. Please use a desktop to view it.",
	YOU_WANT_TO: "Are you sure you want to extend the Due Date ?",
	YOU_WILL_NOT:
		"You will not be able to push the deadline any further. Only 3 more such extensions are left for other submissions.",
	ACKNOWLEDGE_INDIVIDUAL:
		"I acknowledge that I have read and I am in compliance with the academic integrity policy mentioned in the student manual.",
	UPLOADED_FILE_WILL:
		"Uploaded file will be lost if not submitted. Once submitted, the file will be considered as your final submission file.",
	UPLOADED_URL_DESC: "You can not change the URL after submission",
	NO_NOTE_ADDED_TITLE: "No Notes Added Yet ",
	NO_NOTE_DISC:
		"Create notes as you progress through the learning resources.",
	NO_BOOKMARK_TITLE: "No Bookmarks Added",
	NO_BOOKMARK_DISC:
		"Bookmark content as you explore the learning resources. ",
	EXPLORE_NOW: "Explore Now",
	OPTIONAL_ASSET: "Optional",
	PREV_RESOURCE_PENDING: "Previous resource pending",
	CONTENT_EXPIRED: "Content Expired",
	COMING_SOON: "Coming Soon",
	SUBMIT_FOR_EVALUATION: "Submit for Evaluation?",
	PLEASE_CHECK_BACK: ". Please check back then.",
	ASSET_AVAIL_ON: "This learning resource will become available on ",
	ASSET_AVAIL_UNTIL: "This learning resource was only available until ",
	NO_LONGER_AVAIL: " and is no longer accessible.",
	GROUP_NOT_ASSIGNED: "Group not assigned",
	PLEASE_CONTACT_YOUR: "(Please contact your course co-ordinator).",
	EXTENSION_APPLIED_FOR_GROUP:
		"*If this module has a group submission, the extension will not apply to other group members.",
	ACKNOWLEDGE_GROUP:
		"I acknowledge on behalf of my group that we have read and we are in compliance with the academic integrity policy mentioned in the student manual.",
	NOTE_DELETE_WARNING: "Are you sure you want to delete the note?",
	RESTORE_WORNING: "You will never be able to restore it",
	BOOKMARK_DELETE_WARNING: "Are you sure you want to delete the bookmark?",
	TYPE_THE_HEADING: "Type the heading",
	LAST_UPDATE_ON: "Last updated on:",
	REFERENCE_LINKS: "Reference Link:",
	VIEW_ON_DESKTOP_DESC:
		"This asset is not supported on mobile devices. Please access it on a desktop.",
	TIME_TAKEN: "Time Taken",
	WRITE_YOUR_REASON_HERE: "Write your reason here.",
	WANT_YOUR_WORK_TO_BE_REVIEWED_AGAIN: "Want your work to be reviewed again?",
	UPDATE_NOW: "Update Now",
	REMIND_ME_LATER: "Remind me Later",
	RESTART_NOW: "Restart Now",
	LATER: "Later",
	ITS_TIME_TO_UPDATE: "It's Time to Update!",
	GET_THE_LATEST:
		"Get the latest version to enjoy new features and enhancements!",
	PLANNER: "Planner",
	CONTENT_TEXT: "Content",
	MENTORSHIP: "Mentorship",
	PERSONALISED_INDUSTRY: "Personalised Industry",
	DAILY_DOUBT_RESOLUTION: "Daily Doubt Resolution",
	BUDDY_SESSION: "Buddy Session",
	CAREER_COUNSELLING: "Career Counselling",
	DOUBT_RESOLUTION_SESSION: "Doubt Resolution Session",
	LIVE_SESSION: "Live Session",
	OVERDUE: "Overdue",
	PENDING: "Pending",
	OVERDUE_NOT_STARTED: "Overdue not Started",
	OVERDUE_INPROGRESS: "Overdue in Progress",
	START: "Start",
	RESTART: "Restart",
	VIEW_NOTES: "View Notes",
	RE_SCHEDULE_WITHOUT_SPACE: "Reschedule",
	SCHEDULE: "Schedule",
	WATCH_RECORDING: "Watch Recording",
	WATCHED: "Watched",
	CORRECT: "Good Job! You got it right.",
	INCORRECT: "Sorry, that's not correct.",
	SORRY_FOR_INCONVENIENCE:
		"Sorry for the inconvenience. Complete details to continue learning",
	THE_SUBMISSION_DEADLINE_PASSED:
		"The submission deadline has passed for the following sections. Please fill the details to resume learning.",
	WORK_EXPERIENCE: "Work Experience",
	ASPIRATION: "Aspiration",
	YOU_PREFERRED_OPTION_NOT_AVAILABLE:
		"Your preferred option is not available",
	ARE_YOU_SURE_YOU_WANT_TO_ADD:
		"Are you sure you want to add it to the list?",
	SAVED_SUCCESSFULLY: "Saved Successfully",
	FILE_UPLOADED: "File Uploaded",
	CHOOSE_OPTION: "Choose an option",
	PLEASE_ENTER_VALID_VALUE: "Please enter a valid value",
	IM_FRESHER: "I'm a fresher",
	IM_WORKING_SELF_EMPLOYED: "I'm working currently/self-employed",
	HAVE_EXP_NOT_WORKING:
		"I have work experience but have not working currently",
	DOCTORATE: "Doctorate",
	POST_GRADUATION: "Post Graduation",
	GRADUATION: "Graduation",
	CLASS_XII: "Class 12",
	BELOW_CLASS_XII: "Below Class 12",

	GRADUATING_YEAR_TO: "Graduating Year To",
	COLLEGE_UNIVERSITY: "College/University",
	END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR:
		"End Year should be greater than the Start Year",
	SAVING: "Saving...",
	CTC: "CTC",
	THIS_COURSE_IS_PART_OF_ELECTIVE_FROM:
		"This course is a part of an elective which is available for selection from ",
	THIS_COURSE_IS_PART_OF_ELECTIVE_NOW_WHICH_IS_AVAILABLE_NOW:
		"This course is part of an elective for which selection is available now.",
	PLEASE_VISIT_US_ON_DESKTOP_TO_SEE_CURRICULUM_ELECTIVE:
		"Please visit us on a desktop to see the curriculum and choose an elective.",
	PLEASE_SELECT_ELECTIVE_ON_DESKTOP:
		"Please select an elective on a desktop to continue learning.",
	THIS_ELECTIVE_WILL_BE_AVAILABLE_FROM:
		"This elective will be available from ",

	THIS_COURSE_IS_PART_OF_TRACK_FROM:
		"This course is a part of a track which is available for selection from ",
	PLEASE_VISIT_US_ON_DESKTOP_SEE_TRACK:
		"Please visit us on a desktop to see the curriculum and choose a track.",
	THIS_COURSE_IS_PART_OF_TRACK_WHICH_IS_AVAILABLE_NOW:
		"This course is part of a track for which selection is available now.",
	PLEASE_SELECT_TRACK_ON_DESKTOP:
		"Please select a track on a desktop to continue learning.",
	THIS_TRACK_WILL_BE_AVAILABLE_FROM: "This track will be available from ",
	NO_OPTIONS_AVAIL: "No options available",
	TYPE_MIN_3_CHAR: "Type minimum 3 characters to search",
	MAX_128_CHAR: "Must be 128 characters or less",
	DAY: "Day",
	WEEK: "Week",
	MONTH: "Month",
	CUSTOM_DATES: "Custom Dates",
	SELECT_PLACEHOLDER: "--Select-",
	SELECT_START_END_DATE: "Select start and end date range",
	SELECT_CUSTOM_DATES: "Select Custom Dates",
	BACK_TO_HOME: "Back to Home Page",
	MUST_BE_ENROLLED_IN_COURSE:
		"You must be enrolled in a course to use this app.",
	VIEW_LESS: "View Less",
	MIN_WORD_LIMIT_MESSAGE: "Response is required!",
	MAX_WORD_LIMIT_MESSAGE: "Your response exceeds the word limit.",
	DEFAULT: "Default",
	OLD_TO_NEW: "Old to New",
	NEW_TO_OLD: "New to Old",
	SESSIONS: "Sessions",
	CONTAINER: "Container",
	TASK: "Task",
	PROGRAM_NAME: "Program Name",
	RESET_FILTER: "Reset Filter",
	SELECT_ALL: "Select All",
	DUE_DATE_HEADER: "Due Date: ",
	EXPIRES_ON: "Expires On: ",
	URGENT: "Urgent",
	VIDEO_SKIP_VALIDATION: "You cannot skip/forward the video",
	REPORT_AN_ISSUE: "Report an Issue",
	REPORTING_AN_ISSUE_ON: "Reporting an issue on: ",
	TOPIC_NAME: "Topic Name",
	SEGMENT_NAME: "Segment Name",
	MODULE_NAME: "Module Name",
	MILESTONE_MODULE_DETAILS: "Milestone and Module Details",
	WEEK_NO: "Week No",
	USER_FEEDBACK: "User Feedback",
	ISSUE_WITH: "Issue with",
	ASSET_NAME: "Asset Name",
	COURSE_CONTENT: "Course content",
	ASSESSMENT_CONTENT: "Assessment Engine Content",
	SUBMITTING: "Submitting...",
	QUESTION_NAME: "Question Name",
	RECALL_QUIZ_NAME: "Recall Quiz Name",
	PRODUCTIVITY_GPT_TEXT: "Productivity GPT?",
	DOWNLOAD_SOURCE_CODE_FILE: "Download Source Code",
	GO_TO_DESKTOP: "Go To Desktop",
	CALENDAR_VIEW: "Calendar View",
	EXPAND: "Expand",
	COLLAPSE: "Collapse",
	RECORDING_IS_NOT_AVAILABLE: "Recording is not available",
	YOU_CAN_JOIN: "You can join the session 10 minutes before it starts.",
	JOIN_URL_IS_NOT_AVAILABLE: "Join URL is not available",
	NO_EVENTS_FOUND: "No events found!",
	SLOT_SUCCESSFULLY_BOOKED: "Slot successfully booked",
	MEETING_SCHEDULED_WITH_MENTOR: "Scheduled a meeting with Mentor",
	CANCEL_MEETING: "Cancel Meeting",
	CONFIRM_MEETING_CANCELLATION:
		"Are you sure you want to cancel the meeting?",
	CHOOSE_DATE: "Choose Date",
	CHOOSE_TIME: "Choose Time",
	SCHEDULE_MEETING: "Schedule Meeting",
	RESCHEDULE_MEETING: "Reschedule Meeting",
	NO_SLOTS_AVAIL: "No slots available",
	CANCEL_FAILED: "Cancellation failed. Please try again later.",
	CANCEL_SUCCESS: "Cancelled successfully",
	CANT_RESCHEUDLE: "You can not reschedule 1 hour before the session.",
	RESCHEDULE_REQUESTED: "Reschedule Requested",
	HAS_REQUESTED_RESCHEDULE:
		"has requested to reschedule the session and suggested",
	ACCEPT: "Accept",
	DECLINE: "Decline",
	PRODUCTIVITY_GPT: "Productivity GPT",
	PLEASE_ACCESS: "Please access ",
	ON_DESKTOP: "on desktop",
	GOT_IT: "Got it!",
	SCHEDULED_MAINTENANCE: "Scheduled Maintenance",
	THE_LEARNING_PORTAL_WILL_UNAVAILABLE:
		"The learning portal will be unavailable on",
	MARCH_11: "March 11th, 10:00 PM – 4:00 AM (IST)",
	DUE_TO_MAINTENANCE_ACTIVITY: "due to maintenance activity.",
	MAINTENANCE_IN_PROGRESS: "Maintenance in Progress",
	THI_LEARNING_PORTAL_IS_CURRENTLY: "The learning portal is currently",
	UNDERGOING_SCHEDULED_MAINTENANCE: "undergoing scheduled maintenance",
	AND_WILL_BE_BACK_ONLINE: "and will be back online by ",
	SESSION_PARTS: "Session Parts",
	WATCH_AGAIN: "Watch Again",
	BASE_PROGRAM: "Base Program",
	SPECIALIZATION: "Specialization",
	SELECT_NOW: "Select Now",
	SPECIAILIZATON_MODAL_DESC: (specializationCount: number) =>
		`You have enrolled for ${specializationCount} specialisations as part of your course. Log in on your desktop now to complete the selection process.`,
	UPCOMING_SPECIALISATIONS: "Upcoming Specialisations. ",
	BATCH_START_DATE: "Batch Start Date",
	MODULE_TITLE: "Module",
	GRADABLE_CONTENT: "Gradable Content",
	EXTENDED_DUE_DATE: "Extended Due Date",
	COMPLETE_BY_EXTENDED_DUE_DATE:
		"Complete all asessments in this module by the extended due date.",
	COMPLETE_BY_DUE_DATE_MESSAGE:
		"Complete all assessments in this Module by the due date. Late submissions may incur penalty.",
	HIDE: "Hide",
	PENALTY_TIME_FRAMES: "Penalty Time Frames",
	CANT_CANCEL_SESSION: "You can not cancel 1 hour before the session.",
	RESCHEDULE_LIMIT_REACHED:
		"You have reached the maximum number of reschedule requests.",
	BOOK_BY: "Book by",
	ERROR_LOADING_PAGE: "Error loading page",
	VERSION: "Version ",
	APP_VERSION: "App Version",
	PLATFORM_VERSION: "Platform Version",
	DEVICE_NAME: "Device Name",
	DEVICE_PLATFORM: "Device Platform",
	MY_TIMEZONE: "My Timezone",
	MY_TIMEZONE_DESCRIPTION:
		"Updating your timezone will affect how your academic planner and deadlines are displayed.",
	SIGN_IN: "Sign In",
	EXPLORE: "Explore",
	SMARTER_LEARNING_STARTS_HERE: "Smarter learning starts here - try ",
	DOWNLOAD_APP: "Download App",
	DOWNLOAD_APP_DESCRIPTION:
		"Can't see some of your programs? They're just a tap away.",
	FAILED_TO_OPEN_STORE_URL: (storeName: string) =>
		`Failed to open ${storeName} URL.`,
	PLAY_STORE: "Play Store",
	APP_STORE: "App Store",
	IMAGE_NOT_AVAILABLE: "Image not available",
	LEGACY_BETTER_APP_AWAITS: "A Better App Awaits!",
	LEGACY_RETIRE_SOON:
		"This app will be retired soon. Switch to our new app for a faster, smoother learning experience.",
	THIS_IS_CORRECT: "This is Correct!",
	THIS_IS_INCORRECT: "This is Incorrect!",
	LEGACY_DOWNLOAD_NOW: "Download Now",
	LEGACY_LATER: "Nah, I'll do it later.",
	DELETE_ACCOUNT: "Delete Account",
	DELETE_ACCOUNT_HEADING: "Are you sure you want to delete your account?",
	DELETE_ACCOUNT_DESCRIPTION:
		"You'll be logged out immediately and won't be able to log in again. If you change your mind, you have 30 days to contact our support team to recover your account.",
	NEW_APP_DOWNLOAD_DESCRIPTION:
		"Missing Courses? Some courses are under maintenance - use desktop for 4-5 days.",
	THERE_ARE_NO_CHAT_TO_DISPLAY: "There are no chats to display",
	CHAT_IS_DISABLED: "Chat is Disabled!",
	SINCE_THE_SESSION_HAS_ENDED: "Since the session has ended",
	HERE_IS_HOW_YOU_DID: "Here is How You Did!",
	ANSWERED_CORRECTLY: "Answered Correctly",
	RE_TAKE_QUIZ: "Re-Take Quiz",
	UPLOAD_FROM_DESKTOP: "Upload from Desktop",
	LECTURE_: "| LECTURE |",
	UPLOAD_FROM_DESKTOP_DESCRIPTION: (assetType: string) =>
		`Sorry! You can't submit this ${assetType?.toLowerCase()} on the mobile app just yet. Please head to the web to complete your submission. We're working hard to bring this feature to you soon!`,
	EXTENSIONS_USED: "Extensions used",
	WHAT_ARE_EXTENSIONS: "What are Extensions?",
	EXTENSION_INFO_DESCRIPTION: (
		totalExtensions: number,
		usedExtensions: number,
	) =>
		`You can extend the due dates for all assessments within a module. However, extensions are limited—you have a total of ${totalExtensions} module extensions for this program, and you have used ${usedExtensions}.`,
	LANGUAGE: " Language",
	CHAT: " Chat",
	CONTENT_AVAILABLE_ON_WEB: "Content Available on Web",
	YOU_CAN_ACCESS_THIS_SECTION:
		"You can access this section from a desktop browser for now. Mobile access is coming soon!",
	PROFESSIONAL_EXPERIENCE: "Professional Experience",
	VIDEO_FILE_TYPE: "video files (.mp4, .avi)",
	OTHER_FILE: "other files",
	SUBMISSION_TEMPLATE: "Submission Template",
	HELLO_GUEST: "Hello, Guest",
};
